version: '3'

services:
  proxy:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../frontend/build/:/usr/share/nginx/html/:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    # - "/etc/localtime:/etc/localtime:ro"
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'jambox'
      MYSQL_USER: 'jambox'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'secret'
#    ports:
#      - "3306:3306"
    volumes:
      - ./database:/var/lib/mysql
  jambox:
    build: .
#    ports:
#      - "8080:8080"
    restart: on-failure
    volumes:
      - "./tracks:/tracks"
  #      - "/etc/localtime:/etc/localtime:ro"
  


