const PlayerActionTypes = {
  SELECT_TRACK: 'SELECT_TRACK',
  UNSELECT_TRACK: 'UNSELECT_TRACK',
  TOGGLE_PLAYING: 'TOGGLE_PLAYING',
  SET_SHOW_CONTROLS: 'TOGGLE_SHOW_CONTROLS',
};

export default PlayerActionTypes;
