const PlayerActionTypes = {
  SET_PLAYLISTS: 'SET_PLAYLISTS',
  SELECT_TRACK: 'SELECT_TRACK',
  SELECT_NEXT_TRACK: 'SELECT_NEXT_TRACK',
  SELECT_PREVIOUS_TRACK: 'SELECT_PREVIOUS_TRACK',
  UNSELECT_TRACK: 'UNSELECT_TRACK',
  TOGGLE_PLAYING: 'TOGGLE_PLAYING',
  SET_PLAYING: 'SET_PLAYING',
  SET_SHOW_CONTROLS: 'TOGGLE_SHOW_CONTROLS',
};

export default PlayerActionTypes;
