const PlayerActionTypes = {
  SET_PLAYLISTS: 'SET_PLAYLISTS',
  SELECT_TRACK: 'SELECT_TRACK',
  SELECT_NEXT_TRACK: 'SELECT_NEXT_TRACK',
  SELECT_PREVIOUS_TRACK: 'SELECT_PREVIOUS_TRACK',
  UNSELECT_TRACK: 'UNSELECT_TRACK',
  TOGGLE_PLAYING: 'TOGGLE_PLAYING',
  SET_PLAYING: 'SET_PLAYING',
  TOGGLE_SHOW_ARRANGEMENT_VIEW: 'TOGGLE_SHOW_ARRANGEMENT_VIEW',
  SET_ARRANGEMENT: 'SET_ARRANGEMENT',
  TOGGLE_IS_PLAYLIST_COLLAPSED: 'TOGGLE_IS_PLAYLIST_COLLAPSED',
  SET_PLAYLIST_IS_COLLAPSED: 'SET_PLAYLIST_IS_COLLAPSED',
  SET_CURRENT_SONGPART: 'SET_CURRENT_SONGPART',
};

export default PlayerActionTypes;
